#+STARTUP: content
#+OPTIONS: 
#+OPTIONS: toc:nil
# set DATE to void to avoid it's display
#+DATE: 
#+LATEX_CLASS: IEEEtran
#+LaTeX_CLASS_OPTIONS: [journal]
#+LATEX_HEADER: \usepackage{subfig}
# generate roman numbers
#+LATEX_HEADER: \newcommand{\RNum}[1]{\uppercase\expandafter{\romannumeral #1\relax}} 
# bold and italic vector
#+LATEX_HEADER: \newcommand{\vect}[1]{\boldsymbol{#1}}
# In IEEEtran_HOWTO the equations section on page 8. this 2500 config is to estore IEEEtran ability to automatically break within multiline equations
#+LATEX_HEADER: \interdisplaylinepenalty=2500

#+TITLE: A New Look at PCM and APCM

\begin{abstract}
We propose a unified framework for pcm and apcm, from the viewpoint (or by considering?) of uncertainty of the bandwidth parameter. It's shown that the difference between them is how much confidence we have in the data. In fact, the uncertainty of the bandwidth parameter is into the membership of  a point, this is done by using Prof. LiXin Wang's new formulation of the Type 2 fuzzy set, i.e. the conditional fuzzy set framework. Thus this paper also serves as a justify for this new formulation.
\end{abstract}

** PCM and APCM
apcm introduces the concept of smallest physical cluster to cope with the situation where close clusters are equally sized. The unified framework will cope with this situation by noise level.
The main difference(or clustering behavior?) between pcm and apcm is that in apcm we can protect the small cluster from being dragged to the big cluster by manually specifying the bandwidth of the  minimum physical cluster. In this way, if the bandwidth of the small cluster is over-estimated, minimum physical cluster bandwidth will correct it to a lower value, or larger value otherwise.

From formula x, we see that the membership of a point to some cluster is determined by the cluster center and the bandwidth. So we propose that the center update should be modified to avoid being dragged by the large cluster.
** Type 2 fuzzy set
*** introduction of the new formulation of type2 fs
According to Zadeh \cite{zadeh_concept_1975}, a type-2 fuzzy set (T2 FS) is a fuzzy set whose membership values are type-1 fuzzy set on $[0,1]$. When written in more precise mathematical terms,  this definition becomes as follows:
Definition 1 (from \cite{wang_new_2016}): A type-2 fuzzy set $\tilde{X}$ is a fuzzy set defined on the universe of discourse $\Omega_X$ whose membership value $\mu_\tilde{X}(x)$ for a given $x\in\Omega_X$ is a type-1 fuzzy set  $U(x)=\mu_\tilde{X}(x)$ defined on $\Omega_X\subseteq[0,1]$ with membership function \mu_{U(x)}(x,\mu_x) where $\mu_x\in\Omega_X\subseteq[0,1]$. The x is called _primary variable_ and $\mu_x$ is called the _secondary variable_. \qedsymbol

It's clear that T2 FS is just that one fussiness (uncertainty) depends on another fuzziness. However Definition 1 makes T2 FS a complex subject. Recently Li-Xin Wang \cite{wang_new_2016} proposes a conditional fuzzy set framework to define a type-2 fuzzy set. This framework resembles the concept of conditional probability in probability theory, which studies the dependence of one randomness on the other randomness.

In most real-world applications we choose the membership functions to have a fixed structure with some free parameters, such as the Gaussian membership function with the center or standard deviation as free parameters. In such formulations, the uncertainty (fuzziness) of the membership comes from the uncertainties of the free parameters; i.e., the parameter uncertainties are the causes, while the membership uncertainty is the effect, and it is natural to choose the independent cause as the secondary variable to characterize the secondary fuzziness, rather than choosing the dependent effect as the secondary variable.





 
*** The new view offered by the new formulation of type2 fs
**** New interpretation of uncertainty offered by the marginal fs curve.
first say the conclusion from the curve that the more uncertain, the more flat of the mf curve.
if a point is very close to the center, then the corrected bandwidth is almost same as v0, (i.e., the shape is almost same, as we can see from the marginal fuzzy set picture), with the distance to the center increasing, the curve becomes more flat. This is very different from simply specifying a larger bandwidth and is more intuitive.

knowing the uncertainty of the bandwidth doesn't mean that the mf of a point to some cluster becomes more certain.
(Does a pdf share this property? Does the t2mf of Wang only gives this kind of interpretation?)
In contrast, it's difficult to differentiate between  the membership of points far from the center. 远离中心的点的隶属度的区分度没那么大了,即相差没那么大了。

frome the above analysis, we obtain the following definition
Definition 1: A gaussian mf with uncertain bandwidth has the property that, it decreases slower from the center than the true bandwidth. so if we are more certain about the bandwidth, the gaussian will have a more fast decreasing rate. Let's make it more straightforward, a gaussian mf with a uncertain bandwidth is a mf that has a slower decreasing rate of membership from the mode than the mf with the true bandwidth. and the mf will decrease slower when the uncertainty of the bandwidth increases.


From the analysis above, we can conclude that it's reasonable to use the type2 fs to represent the membership of a point to some cluster with uncertain bandwidth. but it's not easy to specify the uncertainty of the bandwidth because we can't even know the true bandwidth. Next we will show that the sigma_v depends on the noise level of the data set.
** The unified Framework
*** introduce the framework

*** Analysis of the parameters
1. 先从最本质的讲起吧。It's too noisy for the smaller cluster in the sense that if all points are used to compute its center (update its center), then the center will be dragged towards the larger cluster because there are more points in the larger cluster. Similarly, the larger cluster is dragged by the smaller cluster in the same way. 
   The $\alpha-\text{cut}$ trick proposed in \cite{krishnapuram_possibilistic_1993} is used to compute the bandwidth with only the "good" feature point , and it's used here to update the center. but if we increase the sigma_v (uncertainty of the bandwidth), its easy to see from the MF figure that the two clusters are in noisy environment again.
2. If the two clusters are closer than in fig.1, then  we have to  specify a larger noise level ( $\alpha$ is large), and the allowed uncertainty of bandwidth is also larger.
   if the noise level is set very high, the bandwidth should be increased in order to search the correct center in dense region and also to enable possible cluster elimination, because a high noise level may indicate that fewer points are actually contributed to the adaption of center.  however the bandwidth shouldn't be too large. ( I have a plot, when bandwidth is not correspondingly increased, an redundant cluster is not eliminated.)
3. this is the way how pcm misses out the smaller cluster. $\alpha$ and sigma_v are used together to constrain each cluster to stay in there clusters ,while still allowing to eliminate clusters in the same dense region.
4. 要先说一下不同noise level下，center 估计误差和 sigma_v的关系。稍微解释一下这个关系
   我初步画图的结果显示，此图正好证实了根据noise level vs 中心估计误差曲线可以判定何时由apcm转化为pcm的。
5. 然后给出一个example来理解这个关系。考多少分能反映一个人的真实水平，if you say that he or she should scores at least 60, you have assumed that the easy degree of the paper is normal. However if the test is very hard, you only need to score say, 30. That is, weather the score would reflect the level of the 考试者 or not depends on the hardness of the test.
6. 引出Type3 FS的必要性。但beyond our scope,因此留给读者来解决。
   Similarly  .for summarize, We can be sure that the uncertainty of bandwidth ( sigma_v ) depends on the noise level, but can we model the relationship between them? For this problem, it's reasonable to use the concept of "Type 3 Fuzzy Set" which doesn't exit up to now, we leave it as an open question for the reader.
   在吃完晚饭的路上，我突然意识到，Type3是一个很难的问题,但我查了一下的确有。我再把上一段修改一下。
   It seems that the bandwidth can also be a Type-2 fuzzy set, and its parameter is the noise level. Can we use the framework of marginal fuzzy set to do this job(i.e. to construct the Type3 fs)? yes we can. now the marginal fuzzy set of the membership u has only one parameter sigma_v, so we can finally cancel out sigma_v if we can model the fuzziness of sigma_v with the noise level as a parameter, we leave it...
   当然还得再补上一句：the fussiness of u depends on the fussiness of the bandwidth, whose fussiness depends on the the noise level, i.e. the Type 3 fuzzy set. It seems feasible to use the framework of marginal fuzzy to （后边接上上一段，哈哈）。
7. 当然我们期望找到噪声程度和sigma_v的关系，这样就可以cancel out sigma_v 了，从而唯一的参数就是从数据中估计出来的noise level啦。
8. 当noise level大的时候，我们得保证一定大的 sigma_v ，使得同一个dense region 中的多个cluster 能够移动到cluster center，同时又不能太大，以防止移动到其他cluster。


#+BEGIN_LaTeX
\bibliographystyle{IEEEtran}
\bibliography{D:/emacs/etc/ZoteroOutput,IEEEabrv}
#+END_LaTeX
